---
- name: Install i-pi dependencies
  become: true
  apt:
    name:
      - build-essential
      - gfortran
      - gcc
      - python-pip

- name: Installing NumPy for i-pi
  become: true
  pip:
    name: NumPy

- name: Get i-pi from github
  git:
    repo: https://github.com/i-pi/i-pi.git
    dest: "{{ i_pi_root_dir }}"
    version: "{{ i_pi_version }}"

- name: Make i-pi drivers
  command: "make"
  args:
    chdir: "{{ i_pi_root_dir }}/drivers"
    creates: "{{ i_pi_root_dir }}/drivers/driver.x"

- name: Copy each file over that matches the given pattern
  copy:
    src: "{{ item }}"
    dest: "/etc/fooapp/"
    owner: "root"
    mode: 0600
  with_fileglob:
    - "/playbooks/files/fooapp/*"

- name: Install i-pi executables
  become: true
  shell: cp {{ i_pi_root_dir }}/bin/* {{ i_pi_prefix }}/bin
  args:
    creates: "{{ i_pi_prefix }}/bin/i-pi"
  register: i_pi_install
