---
- name: Install i-pi dependencies
  become: true
  become_user: "{{ root_user }}"
  apt:
      name: "{{ item }}"
      state: latest
  with_items:
    - build-essential
    - gfortran
    - gcc

- name: Installing NumPy for i-pi
  become: true
  become_user: "{{ root_user }}"
  pip:
      name: NumPy

- name: Get i-pi from github
  git:
    repo: https://github.com/i-pi/i-pi.git
    dest: "{{ i_pi_root_dir}}"
    version: 18b254a9100d47910046ab190c53b89bcecae310

- name: Make i-pi drivers
  shell: "make"
  args:
    chdir: "{{ i_pi_root_dir }}/drivers"
    creates: "{{ i_pi_root_dir }}/drivers/driver.x"
