---
- name: Install i-pi dependencies
  become: true
  become_user: "{{ root_user }}"
  apt:
    name:
      - build-essential
      - gfortran
      - gcc
      - python-pip

- name: Installing NumPy for i-pi
  become: true
  become_user: "{{ root_user }}"
  pip:
    name: NumPy

- name: Get i-pi from github
  git:
    repo: https://github.com/i-pi/i-pi.git
    dest: "{{ i_pi_root_dir }}"
    version: "{{ i_pi_version }}"

- name: Make i-pi drivers
  shell: "make"
  args:
    chdir: "{{ i_pi_root_dir }}/drivers"
    creates: "{{ i_pi_root_dir }}/drivers/driver.x"

- name: "Put a line in ~/.profile to add i-pi to the path"
  lineinfile:
    path: "${HOME}/.profile"
    line: "export PATH=${PATH}:{{ i_pi_root_dir }}/bin/"
